version: "3"

services:
    ui:
        build: ./ui
        ports:
            - "8080:8080"
        volumes:
            - ./ui:/app
            - ./app/node_modules
        stdin_open: true
        tty: true


